name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: macos-14

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release -f:net8.0-maccatalyst

    - name: Publish
      run: dotnet publish -c Release -f:net8.0-maccatalyst

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: Routini.MAUI/bin/Release/net8.0-maccatalyst/publish